name: Send Email on Push

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sendmail
      run: sudo apt-get update && sudo apt-get install -y sendmail

    - name: Debug variables
      run: |
        echo "SMTP_SERVER: $SMTP_SERVER"
        echo "SMTP_PORT: $SMTP_PORT"
        echo "SMTP_USER: $SMTP_USER"
        echo "BRANCH_NAME: $BRANCH_NAME"

    - name: Send email notification
      env:
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        RECIPIENT: 'michu9789p@gmail.com'
        BRANCH_NAME: ${{ github.ref }}
      run: |
        BRANCH_NAME=${BRANCH_NAME#refs/heads/}
        SUBJECT="Changes pushed to branch $BRANCH_NAME"
        BODY="Hello, changes have been pushed to the branch: $BRANCH_NAME."
        echo -e "Subject:$SUBJECT\n\n$BODY" | sendmail -S $SMTP_SERVER:$SMTP_PORT -f "$SMTP_USER" "$RECIPIENT"
